rootProject.name = 'ServicePandaProvider'

apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)

include ':app'

// React Native 0.74+ Gradle Plugin
includeBuild('../node_modules/@react-native/gradle-plugin')