const { Pool } = require('pg');
require('dotenv').config();

// Database configuration
const pool = new Pool({
  connectionString: process.env.DATABASE_URL || 'postgresql://localhost:5432/servicepanda',
});

const dummyProviders = [
  {
    firstName: 'John',
    lastName: 'Smith',
    email: 'john.smith@example.com',
    phone: '0412345678',
    businessName: 'Smith Plumbing Services',
    businessAbn: '12345678901',
    address: '123 Main Street',
    city: 'Brisbane',
    state: 'QLD',
    postcode: '4000',
    serviceCategories: 'Plumbing, Emergency Repairs',
    source: 'manual',
    status: 'new',
    priority: 'high',
    notes: 'Experienced plumber with 10+ years experience',
  },
  {
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@example.com',
    phone: '0423456789',
    businessName: 'Johnson Electrical',
    businessAbn: '23456789012',
    address: '456 Electric Avenue',
    city: 'Gold Coast',
    state: 'QLD',
    postcode: '4217',
    serviceCategories: 'Electrical, Safety Inspections',
    source: 'import',
    importName: 'Gold Coast Campaign',
    status: 'first_call',
    priority: 'medium',
    notes: 'Licensed electrician, specializes in residential work',
  },
  {
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'michael.brown@example.com',
    phone: '0434567890',
    businessName: 'Brown Cleaning Services',
    businessAbn: '34567890123',
    address: '789 Clean Street',
    city: 'Sunshine Coast',
    state: 'QLD',
    postcode: '4551',
    serviceCategories: 'Cleaning, End of Lease',
    source: 'referral',
    status: 'follow_up',
    priority: 'low',
    notes: 'Professional cleaning service, eco-friendly products',
  },
  {
    firstName: 'Emma',
    lastName: 'Wilson',
    email: 'emma.wilson@example.com',
    phone: '0445678901',
    businessName: 'Wilson Landscaping',
    businessAbn: '45678901234',
    address: '321 Garden Road',
    city: 'Cairns',
    state: 'QLD',
    postcode: '4870',
    serviceCategories: 'Landscaping, Garden Maintenance',
    source: 'manual',
    status: 'email',
    priority: 'medium',
    notes: 'Landscape designer with horticulture degree',
  },
  {
    firstName: 'David',
    lastName: 'Taylor',
    email: 'david.taylor@example.com',
    phone: '0456789012',
    businessName: 'Taylor Painting',
    businessAbn: '56789012345',
    address: '654 Paint Lane',
    city: 'Townsville',
    state: 'QLD',
    postcode: '4810',
    serviceCategories: 'Painting, Interior Design',
    source: 'import',
    importName: 'North QLD Campaign',
    status: 'won',
    priority: 'high',
    notes: 'Commercial and residential painting specialist',
  },
  {
    firstName: 'Lisa',
    lastName: 'Anderson',
    email: 'lisa.anderson@example.com',
    phone: '0467890123',
    businessName: 'Anderson Carpentry',
    businessAbn: '67890123456',
    address: '987 Wood Street',
    city: 'Mackay',
    state: 'QLD',
    postcode: '4740',
    serviceCategories: 'Carpentry, Custom Furniture',
    source: 'manual',
    status: 'lost',
    priority: 'low',
    notes: 'Custom furniture maker, 15 years experience',
  },
  {
    firstName: 'James',
    lastName: 'Martinez',
    email: 'james.martinez@example.com',
    phone: '0478901234',
    businessName: 'Martinez Roofing',
    businessAbn: '78901234567',
    address: '147 Roof Terrace',
    city: 'Rockhampton',
    state: 'QLD',
    postcode: '4700',
    serviceCategories: 'Roofing, Gutter Cleaning',
    source: 'referral',
    status: 'new',
    priority: 'urgent',
    notes: 'Emergency roof repairs, 24/7 service',
  },
  {
    firstName: 'Amanda',
    lastName: 'Garcia',
    email: 'amanda.garcia@example.com',
    phone: '0489012345',
    businessName: 'Garcia Pest Control',
    businessAbn: '89012345678',
    address: '258 Pest Free Road',
    city: 'Bundaberg',
    state: 'QLD',
    postcode: '4670',
    serviceCategories: 'Pest Control, Termite Treatment',
    source: 'import',
    importName: 'Central QLD Campaign',
    status: 'first_call',
    priority: 'medium',
    notes: 'Licensed pest controller, eco-friendly solutions',
  },
  {
    firstName: 'Robert',
    lastName: 'Miller',
    email: 'robert.miller@example.com',
    phone: '0490123456',
    businessName: 'Miller HVAC',
    businessAbn: '90123456789',
    address: '369 Air Street',
    city: 'Hervey Bay',
    state: 'QLD',
    postcode: '4655',
    serviceCategories: 'HVAC, Air Conditioning',
    source: 'manual',
    status: 'follow_up',
    priority: 'high',
    notes: 'Commercial HVAC specialist, certified technician',
  },
  {
    firstName: 'Jennifer',
    lastName: 'Davis',
    email: 'jennifer.davis@example.com',
    phone: '0491234567',
    businessName: 'Davis Security',
    businessAbn: '01234567890',
    address: '741 Security Boulevard',
    city: 'Toowoomba',
    state: 'QLD',
    postcode: '4350',
    serviceCategories: 'Security Systems, CCTV',
    source: 'referral',
    status: 'email',
    priority: 'medium',
    notes: 'Security system installer, 10 years experience',
  },
  {
    firstName: 'Christopher',
    lastName: 'Rodriguez',
    email: 'christopher.rodriguez@example.com',
    phone: '0492345678',
    businessName: 'Rodriguez Tiling',
    businessAbn: '12345678901',
    address: '852 Tile Avenue',
    city: 'Gladstone',
    state: 'QLD',
    postcode: '4680',
    serviceCategories: 'Tiling, Bathroom Renovations',
    source: 'manual',
    status: 'new',
    priority: 'low',
    notes: 'Ceramic and porcelain tile specialist',
  },
  {
    firstName: 'Michelle',
    lastName: 'Thompson',
    email: 'michelle.thompson@example.com',
    phone: '0493456789',
    businessName: 'Thompson Locksmith',
    businessAbn: '23456789012',
    address: '963 Lock Street',
    city: 'Maryborough',
    state: 'QLD',
    postcode: '4650',
    serviceCategories: 'Locksmith, Security',
    source: 'import',
    importName: 'Wide Bay Campaign',
    status: 'won',
    priority: 'high',
    notes: '24/7 emergency locksmith service',
  },
  {
    firstName: 'Daniel',
    lastName: 'White',
    email: 'daniel.white@example.com',
    phone: '0494567890',
    businessName: 'White Glass',
    businessAbn: '34567890123',
    address: '159 Glass Road',
    city: 'Gympie',
    state: 'QLD',
    postcode: '4570',
    serviceCategories: 'Glass Repair, Window Replacement',
    source: 'manual',
    status: 'lost',
    priority: 'medium',
    notes: 'Auto and residential glass specialist',
  },
  {
    firstName: 'Nicole',
    lastName: 'Harris',
    email: 'nicole.harris@example.com',
    phone: '0495678901',
    businessName: 'Harris Flooring',
    businessAbn: '45678901234',
    address: '753 Floor Lane',
    city: 'Kingaroy',
    state: 'QLD',
    postcode: '4610',
    serviceCategories: 'Flooring, Carpet Installation',
    source: 'referral',
    status: 'new',
    priority: 'low',
    notes: 'Hardwood and laminate flooring expert',
  },
  {
    firstName: 'Kevin',
    lastName: 'Clark',
    email: 'kevin.clark@example.com',
    phone: '0496789012',
    businessName: 'Clark Concrete',
    businessAbn: '56789012345',
    address: '357 Concrete Drive',
    city: 'Dalby',
    state: 'QLD',
    postcode: '4405',
    serviceCategories: 'Concrete, Driveways',
    source: 'import',
    importName: 'Darling Downs Campaign',
    status: 'first_call',
    priority: 'medium',
    notes: 'Commercial concrete contractor',
  },
  {
    firstName: 'Stephanie',
    lastName: 'Lewis',
    email: 'stephanie.lewis@example.com',
    phone: '0497890123',
    businessName: 'Lewis Fencing',
    businessAbn: '67890123456',
    address: '951 Fence Street',
    city: 'Warwick',
    state: 'QLD',
    postcode: '4370',
    serviceCategories: 'Fencing, Gates',
    source: 'manual',
    status: 'follow_up',
    priority: 'high',
    notes: 'Timber and metal fencing specialist',
  },
  {
    firstName: 'Andrew',
    lastName: 'Robinson',
    email: 'andrew.robinson@example.com',
    phone: '0498901234',
    businessName: 'Robinson Solar',
    businessAbn: '78901234567',
    address: '264 Solar Avenue',
    city: 'Roma',
    state: 'QLD',
    postcode: '4455',
    serviceCategories: 'Solar Installation, Energy',
    source: 'referral',
    status: 'email',
    priority: 'urgent',
    notes: 'Solar panel installer, certified technician',
  },
  {
    firstName: 'Rebecca',
    lastName: 'Walker',
    email: 'rebecca.walker@example.com',
    phone: '0499012345',
    businessName: 'Walker Irrigation',
    businessAbn: '89012345678',
    address: '468 Water Road',
    city: 'Chinchilla',
    state: 'QLD',
    postcode: '4413',
    serviceCategories: 'Irrigation, Sprinkler Systems',
    source: 'manual',
    status: 'new',
    priority: 'low',
    notes: 'Agricultural and residential irrigation',
  },
  {
    firstName: 'Joshua',
    lastName: 'Perez',
    email: 'joshua.perez@example.com',
    phone: '0490123456',
    businessName: 'Perez Welding',
    businessAbn: '90123456789',
    address: '753 Metal Street',
    city: 'Emerald',
    state: 'QLD',
    postcode: '4720',
    serviceCategories: 'Welding, Metal Fabrication',
    source: 'import',
    importName: 'Central Highlands Campaign',
    status: 'won',
    priority: 'medium',
    notes: 'Industrial and structural welding',
  },
  {
    firstName: 'Laura',
    lastName: 'Hall',
    email: 'laura.hall@example.com',
    phone: '0491234567',
    businessName: 'Hall Upholstery',
    businessAbn: '01234567890',
    address: '159 Fabric Lane',
    city: 'Longreach',
    state: 'QLD',
    postcode: '4730',
    serviceCategories: 'Upholstery, Furniture Repair',
    source: 'manual',
    status: 'lost',
    priority: 'low',
    notes: 'Antique furniture restoration specialist',
  }
];

async function addDummyProviders() {
  try {
    console.log('Adding dummy potential providers...');
    
    for (const provider of dummyProviders) {
      const query = `
        INSERT INTO potential_providers (
          first_name, last_name, email, phone, business_name, business_abn,
          address, state, city, postcode, service_categories, source,
          import_name, status, priority, notes, created_at, updated_at
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, NOW(), NOW())
      `;
      
      const values = [
        provider.firstName,
        provider.lastName,
        provider.email,
        provider.phone,
        provider.businessName,
        provider.businessAbn,
        provider.address,
        provider.state,
        provider.city,
        provider.postcode,
        provider.serviceCategories,
        provider.source,
        provider.importName || null,
        provider.status,
        provider.priority,
        provider.notes,
      ];
      
      await pool.query(query, values);
      console.log(`Added: ${provider.firstName} ${provider.lastName} - ${provider.businessName}`);
    }
    
    console.log(`Successfully added ${dummyProviders.length} dummy potential providers`);
  } catch (error) {
    console.error('Error adding dummy providers:', error);
  } finally {
    await pool.end();
  }
}

addDummyProviders();
